name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Use the virtual environment
          source .venv/bin/activate

          # Export github secrets to environment variables
          export DATABRICKS_CLIENT_ID=${{ secrets.DATABRICKS_CLIENT_ID }}
          export DATABRICKS_CLIENT_SECRET=${{ secrets.DATABRICKS_CLIENT_SECRET }}
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}

          # Run tests
          pytest
